name: ffi
version: 1.2.0
description: Utilities for working with Foreign Function Interface (FFI) code.
repository: https://github.com/dart-lang/ffi

environment:
  sdk: '>=2.16.0<3.0.0'

dev_dependencies:
  test: ^1.16.0
  lints: ^1.0.0
