name: ffi
version: 1.0.0
homepage: https://github.com/dart-lang/ffi
description: Utilities for working with Foreign Function Interface (FFI) code.

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
